Not using distributed mode
Creating vqa datasets
Creating model
load checkpoint from /home/admin1/5703-upload/5703/Transformer_VQA_no/output_vqa2/vqa/checkpoint_07.pth ,evaluate.
<All keys matched successfully>
Start training
['where is he looking', 'what are the people in the background doing', 'what is he on top of', 'what website copyrighted the picture', 'is this a creamy soup', 'is this rice noodle soup', 'what is to the right of the soup', 'what is the man doing in the street']
['down[SEP]', 'spectating[SEP]', 'table[SEP]', 'foodiebakercom[SEP]', 'no[SEP]', 'yes[SEP]', 'chopsticks[SEP]', 'crossing it[SEP]']
['down[SEP]', 'watching[SEP]', 'table[SEP]', 'foodiebakercom[SEP]', 'no[SEP]', 'yes[SEP]', 'chopsticks[SEP]', 'walking[SEP]']
['at table[SEP]', 'watching[SEP]', 'table[SEP]', 'foodiebaker[SEP]', 'no[SEP]', 'yes[SEP]', 'chopsticks[SEP]', 'walking[SEP]']
['skateboard[SEP]', 'watching[SEP]', 'picnic table[SEP]', 'foodiebakercom[SEP]', 'no[SEP]', 'yes[SEP]', 'chopsticks[SEP]', 'crossing[SEP]']
['down[SEP]', 'watching[SEP]', 'picnic table[SEP]', 'foodiebakercom[SEP]', 'no[SEP]', 'yes[SEP]', 'chopsticks[SEP]', 'crossing road[SEP]']
['table[SEP]', 'watching[SEP]', 'picnic table[SEP]', 'http: foodiebakercom[SEP]', 'no[SEP]', 'yes[SEP]', 'shrimp[SEP]', 'walking[SEP]']
['down[SEP]', 'watching[SEP]', 'picnic table[SEP]', 'foodiebakercom[SEP]', 'no[SEP]', 'yes[SEP]', 'chopsticks[SEP]', 'crossing[SEP]']
['down[SEP]', 'watching[SEP]', 'picnic table[SEP]', 'foodiebakercom[SEP]', 'no[SEP]', 'yes[SEP]', 'chopsticks[SEP]', 'walking[SEP]']
Generate VQA test result:  [    0/26794]  eta: 7:11:39  acc: 0.0000  time: 0.9666  data: 0.3925  max mem: 4164
Traceback (most recent call last):
  File "/home/admin1/5703-upload/5703/Transformer_VQA_no/run_vqa2.py", line 400, in <module>
    main(args, config)
  File "/home/admin1/5703-upload/5703/Transformer_VQA_no/run_vqa2.py", line 359, in main
    vqa_result = evaluation(model, test_loader, tokenizer, device, config)
  File "/home/admin1/anconda3/envs/pytorch2.0/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/admin1/5703-upload/5703/Transformer_VQA_no/run_vqa2.py", line 136, in evaluation
    for n, (image, question, question_id,ans) in enumerate(metric_logger.log_every(data_loader, print_freq, header)):
  File "/home/admin1/5703-upload/5703/Transformer_VQA_no/utils.py", line 137, in log_every
    for obj in iterable:
  File "/home/admin1/anconda3/envs/pytorch2.0/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/home/admin1/anconda3/envs/pytorch2.0/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1325, in _next_data
    return self._process_data(data)
  File "/home/admin1/anconda3/envs/pytorch2.0/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/admin1/anconda3/envs/pytorch2.0/lib/python3.9/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/home/admin1/anconda3/envs/pytorch2.0/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/admin1/anconda3/envs/pytorch2.0/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/home/admin1/anconda3/envs/pytorch2.0/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 265, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/home/admin1/anconda3/envs/pytorch2.0/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 142, in collate
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/home/admin1/anconda3/envs/pytorch2.0/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 142, in <listcomp>
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/home/admin1/anconda3/envs/pytorch2.0/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 138, in collate
    raise RuntimeError('each element in list of batch should be of equal size')
RuntimeError: each element in list of batch should be of equal size