Not using distributed mode
Creating vqa datasets
Traceback (most recent call last):
  File "/home/admin1/5703-upload/5703/Transformer_VQA_no/run_vqa2.py", line 368, in <module>
    main(args, config)
  File "/home/admin1/5703-upload/5703/Transformer_VQA_no/run_vqa2.py", line 181, in main
    datasets = create_dataset('vqa', config)
  File "/home/admin1/5703-upload/5703/Transformer_VQA_no/dataset/__init__.py", line 53, in create_dataset
    train_dataset = vqa_dataset(config['train_file'], train_transform,config['data_root'], split='train')
  File "/home/admin1/5703-upload/5703/Transformer_VQA_no/dataset/vqa_dataset.py", line 14, in __init__
    self.ann += json.load(open(f,'r'))
  File "/home/admin1/anconda3/envs/pytorch2.0/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/home/admin1/anconda3/envs/pytorch2.0/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/admin1/anconda3/envs/pytorch2.0/lib/python3.9/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 108918081 (char 108918080)